#define MAX_THREAD_COUNT 500
#define MAX_ALLOC_COUNT 100000
//#define START_ON_CONSTRUCT
#define USE_AUTO_THREAD_START
//#define START_ON_ENV

#define TRANSFER_MODE_TCP 1
#define TRANSFER_MODE_UDP 1
#define TRANSFER_MODE_NAMEDPIPE 1
#define TRANSFER_MODE_USED TRANSFER_MODE_NAMEDPIPE
#define NAMED_PIPE_FILE "/tmp/aleakd.namedpipe"

#define BUFFERIZE_TRANSFERT