#define TRANSFER_MODE_TCP 1
#define TRANSFER_MODE_UDP 2
#define TRANSFER_MODE_NAMEDPIPE 3
#define TRANSFER_MODE_USED TRANSFER_MODE_NAMEDPIPE
#define NAMED_PIPE_FILE "/tmp/aleakd.namedpipe"

#define BUFFERIZE_TRANSFERT
#define BACKTRACE_MAX_SIZE 50